### ISSUE TITLE
Single file gets tailed

### ISSUE THREAD

**Issue by DavidAntaramian** [timberio/agent#112]
I introduced a bug in 0.4.0 that caused only the last specified file in a configuration to be tailed, regardless of how many files were specified. The changes being made in #111 by Ben should fix this, however, I wanted to track this bug separately from the file globbing issue in #58 so that anyone affected by the bug can follow along.

Due to the changes in #111 and still being pre-1.0, we'll probably fix this in 0.5 despite it being a bug affecting 0.4.

**Comment by binarylogic** [comment]
Confirmed that https://github.com/timberio/agent/pull/111 resolves this issue.

**Comment by DavidAntaramian** [comment]
For future reference, this is fixed in 0.5.0 and above.

**Comment by binarylogic** [comment]
Reopening as we're seeing this behaviour again in `0.5.2`.
