### ISSUE TITLE
Status code 413 when uploading logs

### ISSUE THREAD

**Issue by rdb** [timberio/agent#139]
When trying to use `timber-agent capture-files` on new logs that are large (10 MB), it seems to fail to separate up the file properly into multiple buffers for separate upload, resulting in a 413 error message and the logs never arriving:

```
2018/04/20 13:47:19 [DEBUG] POST https://logs.timber.io/frames
time="2018-04-20T13:47:19Z" level=fatal msg="unexpected response (status code 413)"
```

**Comment by binarylogic** [comment]
Thanks for reporting, I have a feeling this is related to our internal Nginx configuration. We'll take a look and report back.

**Comment by binarylogic** [comment]
Actually I stand corrected, it appears to be an agent issue. We're going to add a test specifically for this and see if we can reproduce.

**Comment by carkmorwin** [comment]
@rdb Based on local testing I have done, this error appears to show up when the logline to be shipped is greater than 1MB. Can you confirm this?

**Comment by carkmorwin** [comment]
@rdb We have decided to move forward and drop messages greater than 1MB, which again was the way I recreated the issue. As of now, there are also no plans for supporting chunking of messages greater than 1MB in the agent.

**Comment by rdb** [comment]
Thank you. I will let you know if I am able to recreate this error.
