### ISSUE TITLE
Failing all retries should not hard kill the agent

### ISSUE THREAD

**Issue by carkmorwin** [timberio/agent#154]
Currently when we reach our retry limit for sending to the timber backend, if we receive an error the agent quits. Depending on the error we should still fail or continue running with backoff. 

For example, in the case of an auth error, config is not correct and we should exit since it will never be right until restart. If the backend is not responsive we should try again with backoff until we can send again.

**Comment by jralph** [comment]
+1 for this. Just experiencing this now with logs.timber.io being down.
