### ISSUE TITLE
0.9.0 Agent is using 100x more CPU over 0.8.x agent

### ISSUE THREAD

**Issue by carkmorwin** [timberio/agent#161]
Most likely this is due to introducing `tail.Tell()` call when reading each log line. 

I will confirm CPU usage increase as well as spec out a fix.

**Comment by carkmorwin** [comment]
@jralph Can you post the results from `uname -a` on the machine where the agent is running. Also what filesystem is it running on?

**Comment by jralph** [comment]
@carkmorwin 

```
uname -a
Linux xxxxx 4.4.0-1060-aws #69-Ubuntu SMP Sun May 20 13:42:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

It's running on docker using mounted volumes to access the files it needs to tail.

**Comment by carkmorwin** [comment]
@jralph Thanks for the info and sorry for the delay on this. A PR is out now that should get merged tomorrow EST (7/26). Once done, a new version of the agent will be cut and released.

**Comment by jralph** [comment]
@carkmorwin Thats great, thanks for the quick fix on this!

**Comment by carkmorwin** [comment]
@jralph `v0.9.1` is live and should address CPU issues. I've confirmed this in test but if that's not the case in your environment, let us know.
