### ISSUE TITLE
Timber daemonset fails due to path mount

### ISSUE THREAD

**Issue by jbunce** [timberio/agent#169]
`kubectl apply -f https://raw.githubusercontent.com/timberio/agent/master/support/scripts/kubernetes/timber-agent-daemonset-rbac.yaml` fails with:

```
Error: failed to start container "timber-agent": Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/etc/hostname\\\" to rootfs \\\"/var/lib/docker/overlay2/1bc84744efebbd2fc263b5cbebce9501f6c204c7dc57265f1cd0d06853e1d914/merged\\\" at \\\"/var/lib/docker/overlay2/1bc84744efebbd2fc263b5cbebce9501f6c204c7dc57265f1cd0d06853e1d914/merged/etc/hostname\\\" caused \\\"not a directory\\\"\""
: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```
Kubernetes v1.9.7-gke.7 on GCP

**Comment by jbunce** [comment]
I deployed this by removing the `/etc/hostname` volume mount, but this should probably be changed for new users attempting to deploy on GCP

**Comment by carkmorwin** [comment]
@jbunce Thanks for reporting this.

Do you know if/where the hostname is stored on the kubernetes gcp instances? If not, I will look into further. 

We use the hostname to populate metadata the agent ships along with the logs and found/thought /etc/hostname was a reliable place to get that info. Either way, I will update the installation documentation and the kubernetes manifests.

**Comment by carkmorwin** [comment]
@jbunce sorry for the delay in fixing this. The docs have been updated and a kubernetes manifest has been created which removes the `/etc/hostname` mount. 

https://docs.timber.io/platforms/kubernetes/troubleshooting/#google-kubernetes-engine-(gke)---failed-to-create-rbac-resources
