### ISSUE TITLE
Allow user to specify polling to overcome file watching issues

### ISSUE THREAD

**Issue by DavidAntaramian** [timberio/agent#19]
The tailing library we use for the agent (github.com/hpcloud/tail) depends on the `fsnotify` (github.com/fsnotify/fsnotify) library for determining when a file changes. In turn, the `fsnotify` library relies on operating system support for monitoring file changes. On Linux this is `inotify` and on BSD-style systems this is `kqueue`.

The problem is that this doesn't always work. Different environment issues (including containerization) will result in file changes not being reported. In this case, the polling system that ships with tailing needs to be used. This just polls the file for changes on a regular basis.

I think this switch should be global. For example, from the command line:

```
timber-agent --use-polling
```

Config file:

```toml
use_polling = true
```

**Comment by carkmorwin** [comment]
This has already been implemented, closing issue.

https://github.com/timberio/agent/blob/master/config.go#L24
