### ISSUE TITLE
Map AWS EB environments to Timber applications

### ISSUE THREAD

**Issue by binarylogic** [timberio/agent#32]
Currently, our strategy for setting up the Timber agent within the AWS EB environment offers a one to one mapping with an EB app and a Timber app. This won't work because EB apps can have multiple environments, and each environment should map to the proper Timber app.

AWS [provides variables to access the environment](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environment-resources.html) during configuration, and our agent setup should account for this.

**Comment by DavidAntaramian** [comment]
This issues was superseded in large part by #36, however I'm keeping it open until we confirm that #36 suitable implements all our needs.

**Comment by DavidAntaramian** [comment]
Closing this based on soon-to-be-released documentation that uses [`Fn::GetOptionSetting`](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/ebextensions-functions.html#ebextensions-functions-getoptionsetting)
