### ISSUE TITLE
Capture AWS instance metadata

### ISSUE THREAD

**Issue by binarylogic** [timberio/agent#34]
This is useful data we can include in the metadata header: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html

All of this should be placed in the `context.system` document.

**Comment by DavidAntaramian** [comment]
We've decided that instance metadata will instead be placed in the `context.platform.aws_ec2` key.

The following data will be recorded:

  - `ami_id`
  - `hostname` (this is the hostname assigned by AWS; it is not necessarily what the host will report its hostname to be)
  - `instance_id`
  - `instance_type`
  - `public_hostname` (public hostname routed through AWS DNS)
  - `security_groups`

**Comment by DavidAntaramian** [comment]
Removing `security_groups` because we can't support arrays in the log metadata currently
